## 解决在 vue 中 axios 请求超时的问题

自从使用 Vue2 之后，就使用官方推荐的 axios 的插件来调用 API，在使用过程中，如果服务器或者网络不稳定掉包了, 你们该如何处理呢? 下面我给你们分享一下我的经历。

### 具体原因
最近公司在做一个项目, 服务端数据接口用的是 java 输出的 API, 有时候在调用的过程中会失败, 在谷歌浏览器里边显示 Provisional headers are shown。

按照搜索引擎给出来的解决方案，解决不了我的问题.

最近在研究 AOP 这个开发编程的概念，axios 开发说明里边提到的栏截器 (axios.Interceptors) 应该是这种机制，降低代码耦合度，提高程序的可重用性，同时提高了开发的效率。

### 带坑的解决方案一
我的经验有限，觉得唯一能做的，就是 axios 请求超时之后做一个重新请求。通过研究 axios 的使用说明，给它设置一个 timeout = 6000

```javascript
axios.defaults.timeout =  6000
```
然后加一个栏截器.

```
// Add a request interceptor
axios.interceptors.request.use(function (config) {
    // Do something before request is sent
    return config
  }, function (error) {
    // Do something with request error
    return Promise.reject(error)
})

// Add a response interceptor
axios.interceptors.response.use(function (response) {
    // Do something with response data
    return response
  }, function (error) {
    // Do something with response error
    return Promise.reject(error)
})
```

这个栏截器作用是 如果在请求超时之后，栏截器可以捕抓到信息，然后再进行下一步操作，也就是我想要用 重新请求。

这里是相关的页面数据请求。

```
this.$axios.get(url, {params:{load:'noload'}}).then(function (response) {
    //dosomething()
}).catch(error => {
    // 超时之后在这里捕抓错误信息.
    if (error.response) {
        console.log('error.response')
        console.log(error.response)
    } else if (error.request) {
        console.log(error.request)
        console.log('error.request')
        if(error.request.readyState == 4 && error.request.status == 0){
            // 我在这里重新请求
        }
    } else {
        console.log('Error', error.message)
    }
    console.log(error.config)
})

```
超时之后, 报出 `Uncaught (in promise) Error: timeout of xxx ms exceeded` 的错误。

在 catch 那里，它返回的是 error.request 错误，所以就在这里做 retry 的功能, 经过测试是可以实现重新请求的功功能， 虽然能够实现 超时重新请求的功能，但很麻烦，需要每一个请 API 的页面里边要设置重新请求。

如果项目有几十个.vue 文件，如果每个页面都要去设置超时重新请求的功能，那我要疯掉的.
 
而且这个机制还有一个严重的 bug，就是被请求的链接失效或其他原因造成无法正常访问的时候，这个机制失效了，它不会等待我设定的 6 秒，而且一直在刷，一秒种请求几十次，很容易就把服务器搞垮了，请看下图, 一眨眼的功能，它就请求了 146 次。

---

### 带坑的解决方案二
研究了 `axios` 的源代码，超时后, 会在拦截器那里 `axios.interceptors.response` 捕抓到错误信息, 且 `error.code = "ECONNABORTED"`，具体链接

https://github.com/axios/axios/blob/26b06391f831ef98606ec0ed406d2be1742e9850/lib/adapters/xhr.js#L95-L101

```
    // Handle timeout
    request.ontimeout = function handleTimeout() {
      reject(createError('timeout of' + config.timeout + 'ms exceeded', config, 'ECONNABORTED',
        request))

      // Clean up request
      request = null
    }
```

所以，我的全局超时重新获取的解决方案这样的。

```javascript
axios.interceptors.response.use(function(response) {
  // ...
}, function(error){
    const originalRequest = error.config
    if(error.code === 'ECONNABORTED' && error.message.indexOf('timeout') !== -1 && !originalRequest._retry){
            originalRequest._retry = true
            return axios.request(originalRequest)
    }
})
```

这个方法，也可以实现得新请求，但有两个问题，1 是它只重新请求 1 次，如果再超时的话，它就停止了，不会再请求。第 2 个问题是，我在每个有数据请求的页面那里，做了许多操作，比如 `this.$axios.get(url).then` 之后操作。

---
### 完美的解决方法
以 `AOP` 编程方式，我需要的是一个 超时重新请求的全局功能， 要在 `axios.Interceptors` 下功夫，在 `Github` 的 `axios` 的 `issue` 找了别人的一些解决方法，终于找到了一个完美解决方案，就是下面这个。

https://github.com/axios/axios/issues/164#issuecomment-327837467

```
// 在 main.js 设置全局的请求次数，请求的间隙
axios.defaults.retry = 4
axios.defaults.retryDelay = 1000

axios.interceptors.response.use(undefined, function axiosRetryInterceptor(err) {
    var config = err.config
    // If config does not exist or the retry option is not set, reject
    if(!config || !config.retry) return Promise.reject(err)
    
    // Set the variable for keeping track of the retry count
    config.__retryCount = config.__retryCount || 0
    
    // Check if we've maxed out the total number of retries
    if(config.__retryCount>= config.retry) {
        // Reject with the error
        return Promise.reject(err)
    }
    
    // Increase the retry count
    config.__retryCount += 1
    
    // Create new promise to handle exponential backoff
    var backoff = new Promise(function(resolve) {
        setTimeout(function() {
            resolve()
        }, config.retryDelay || 1)
    })
    
    // Return the promise in which recalls axios to retry the request
    return backoff.then(function() {
        return axios(config)
    })
})
```
其他的那个几十个 `.vue` 页面的 `this.$axios` 的 `get` 和 `post` 的方法根本就不需要去修改它们的代码。

 

参考文章：https://juejin.im/post/5abe0f94518825558a06bcd9

关注前端开发 关注用户体验 请访问我的新博客: https://www.cssge.com
